### ISSUE TITLE
terminal error on compile

### ISSUE THREAD

**Issue by MarkKleinfelder** [Astroknut/Project3#19]
I'm working on the call to the Watson API. Everything was working until we tried to resolve some pull/merge issues. After removing and recreating the watson.service file and related component, I'm getting this error when compiling:

ERROR in vendor.a5efcf726a74a6bbd529.bundle.js from UglifyJs
Unexpected token: name (options) [vendor.a5efcf726a74a6bbd529.bundle.js:18092,6]

The app compiles and launches if I comment out all of the watson.service references in the related component. It looks identical to past commits that have worked and I've deleted the package-lock.json, and run npm install. 

Any ideas?

**Comment by ZebGirouard** [comment]
Hi @MarkKleinfelder , I would advise you to make a tiny change in your `npm start`: try `ng build --dev` instead of `ng build --prod` when you start up the project.  That way, you can see the error in a fully readable file.
