### ISSUE TITLE
Observable in service doesn't update

### ISSUE THREAD

**Issue by cg923** [Astroknut/Project3#20]
Hi guys.  So, I have a service that handles all the journals in our app.  Right now it's all dummy data, an array in my journal.service.

My journal.service has a subject
`  public subject: Subject<any> = new Subject();
`
And my component subscribes to it as such:
`this.journalService.getObservable().subscribe(journals => {
      this.journals = journals;
 });`

A separate component calls a function within the service that adds another journal to the array, and then the subject in the service .next's the new value.
But when I switch back to that first component..... the new journal is gone.

I have read the following articles to try to understand the correct way to set up observables:
https://angular-2-training-book.rangle.io/handout/observables/using_observables.html
https://stackoverflow.com/questions/37174598/how-to-get-last-value-when-subscribing-to-an-observable (<----- Not sure if related or not)

I talked with Stefan about this for over an hour and he was totally stumped.  I would really love some help on this!

**Comment by ZebGirouard** [comment]
I talked with Corey for almost an hour as well.  Yeah, no clue how to resolve this.

**Comment by cg923** [comment]
Unfortunately the resolution to this issue is, indeed, that once I actually had my service hit back-end routes instead of storing front-end dummy data, the problem went away...

... but only because I stopped using this code.  So, unfortunately this remains a mystery but it is no longer a problem.

Thank you for your extensive help, Zeb, even if we couldn't figure it out!
