### ISSUE TITLE
ALL JOURNALS master list?

### ISSUE THREAD

**Issue by samascher** [Astroknut/Project3#32]
hey guys! i really like your "view all journals" format -- any chance you could make the slider between them more clear, or perhaps, the name of the journal larger? if you made an ALL JOURNALS list on the side of the page - then the user could also click directly to the journal theyd like and not have to scroll.

great job!!

**Comment by cg923** [comment]
Great suggestion Sam.  I made the journal titles bigger and added a list view at the bottom of the page.  Thanks for the idea!
